---
- name: Extract AWX Host Data and Push to Grafana
  hosts: localhost
  gather_facts: no
  connection: local
  become: no

  vars:
    postgres_host: "{{ AWX_POSTGRES_HOST | default(lookup('env', 'AWX_POSTGRES_HOST')) }}"
    postgres_port: "{{ AWX_POSTGRES_PORT | default(lookup('env', 'AWX_POSTGRES_PORT') | default('5432')) }}"
    postgres_db: "{{ AWX_POSTGRES_DB | default(lookup('env', 'AWX_POSTGRES_DB') | default('awx')) }}"
    postgres_user: "{{ AWX_POSTGRES_USER | default(lookup('env', 'AWX_POSTGRES_USER') | default('awx')) }}"
    postgres_password: "{{ AWX_POSTGRES_PASSWORD | default(lookup('env', 'AWX_POSTGRES_PASSWORD')) }}"
    inventory_name: "{{ awx_inventory_name | default('test-inv') }}"
    grafana_url: "{{ GRAFANA_URL | default(lookup('env', 'GRAFANA_URL')) }}"
    grafana_token: "{{ GRAFANA_TOKEN | default(lookup('env', 'GRAFANA_TOKEN')) }}"

  pre_tasks:
    - name: Validate required variables
      assert:
        that:
          - postgres_host is defined and postgres_host | length > 0
          - grafana_url is defined and grafana_url | length > 0
          - grafana_token is defined and grafana_token | length > 0
        fail_msg: "Missing required environment variables"

  tasks:
    - name: Install required Python packages
      pip:
        name:
          - psycopg2-binary
          - requests
        state: present
      ignore_errors: yes

    - name: Query AWX PostgreSQL database using psql
      shell: |
        export PGPASSWORD="{{ postgres_password }}"
        psql -h {{ postgres_host }} -U {{ postgres_user }} -d {{ postgres_db }} -t -c "
        SELECT json_agg(row_to_json(t))
        FROM (
          SELECT 
            h.id,
            h.name,
            h.variables
          FROM main_host h
          JOIN main_inventory i ON h.inventory_id = i.id
          WHERE i.name = '{{ inventory_name }}'
          ORDER BY h.name
        ) t
        "
      register: db_query_result
      ignore_errors: yes
      changed_when: false

    - name: Parse database query result
      set_fact:
        hosts_data: "{{ db_query_result.stdout | from_json | default([]) }}"
      ignore_errors: yes

    - name: Set empty list if query failed
      set_fact:
        hosts_data: []
      when: hosts_data is not defined or hosts_data is none

    - name: DEBUG - Show queried hosts
      debug:
        msg: |
          Found {{ hosts_data | length }} hosts
          {% for host in hosts_data %}
          - {{ host.name }}
          {% endfor %}

    - name: Show database query error if failed
      debug:
        msg: "Database query output: {{ db_query_result.stdout }}"
      when: db_query_result.rc | default(0) != 0

    - name: Push host data to Grafana as annotations
      uri:
        url: "{{ grafana_url }}/api/annotations"
        method: POST
        headers:
          Authorization: "Bearer {{ grafana_token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          dashboardId: 0
          panelId: 0
          tags:
            - "zammad_inventory"
            - "{{ item.name }}"
          text: |
            **Host:** {{ item.name }}
            Zammad: {{ (item.variables | from_json).zammad_info.zammad_version | default('-') }}
            Redis: {{ (item.variables | from_json).redis_info.version | default('-') }}
            Elasticsearch: {{ (item.variables | from_json).elasticsearch_info.version | default('-') }}
            RAM: {{ (item.variables | from_json).zammad_info.ram_gb | default('-') }} GB
            Status: {{ 'Active' if (item.variables | from_json).zammad_info.zammad_active else 'Inactive' }}
            OS: {{ (item.variables | from_json).zammad_info.os | default('-') }}
            IP: {{ (item.variables | from_json).zammad_info.ip_address | default('-') }}
            Owner: {{ (item.variables | from_json).zammad_info.owner | default('-') }}
          time: "{{ ansible_date_time.epoch | int }}000"
        validate_certs: no
      loop: "{{ hosts_data }}"
      when: hosts_data | length > 0
      ignore_errors: yes

    - name: Display summary
      debug:
        msg: |
          ========================================
          AWX to Grafana Push Complete
          ========================================
          Hosts processed: {{ hosts_data | length }}
          Grafana URL: {{ grafana_url }}
          
          Annotations created for:
          {% for host in hosts_data %}
          - {{ host.name }}
          {% endfor %}
          
          Timestamp: {{ ansible_date_time.iso8601 }}
          ========================================