---
- name: Export AWX Inventory Hosts to Grafana
  hosts: localhost
  gather_facts: no
  connection: local
  become: no

  collections:
    - community.postgresql

  vars:
    # PostgreSQL credentials from environment variables
    postgres_host: "{{ lookup('env','POSTGRES_HOST') }}"
    postgres_port: "{{ lookup('env','POSTGRES_PORT') | default('5432') }}"
    postgres_db: "{{ lookup('env','POSTGRES_DB') | default('awx') }}"
    postgres_user: "{{ lookup('env','POSTGRES_USER') }}"
    postgres_password: "{{ lookup('env','POSTGRES_PASSWORD') }}"
    # Grafana credentials
    grafana_url: "{{ lookup('env','GRAFANA_URL') }}"
    grafana_token: "{{ lookup('env','GRAFANA_TOKEN') }}"
    # Inventory to export
    awx_inventory_name: "{{ lookup('env','AWX_INVENTORY') | default('test-inv') }}"

  pre_tasks:
    - name: Validate required environment variables
      assert:
        that:
          - postgres_host is defined
          - postgres_user is defined
          - postgres_password is defined
          - grafana_url is defined
          - grafana_token is defined
        fail_msg: "Missing required environment variables!"

  tasks:

    - name: Query AWX inventory hosts
      community.postgresql.postgresql_query:
        login_host: "{{ postgres_host }}"
        login_port: "{{ postgres_port }}"
        login_user: "{{ postgres_user }}"
        login_password: "{{ postgres_password }}"
        db: "{{ postgres_db }}"
        query: |
          SELECT h.id, h.name, h.variables
          FROM main_host h
          JOIN main_inventory i ON h.inventory_id = i.id
          WHERE i.name = %s
          ORDER BY h.name
        positional_args:
          - "{{ awx_inventory_name }}"
      register: db_hosts
      no_log: true

    - name: Parse host variables
      set_fact:
        parsed_hosts: >-
          {{
            db_hosts.query_result | map('combine', {'vars': (item.variables | from_json if item.variables else {}) }) | list
          }}

    - name: Show host count
      debug:
        msg: "Found {{ parsed_hosts | length }} hosts in inventory '{{ awx_inventory_name }}'"

    - name: Push each host to Grafana annotations
      uri:
        url: "{{ grafana_url }}/api/annotations"
        method: POST
        headers:
          Authorization: "Bearer {{ grafana_token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          tags:
            - "awx_inventory"
            - "{{ awx_inventory_name }}"
            - "{{ item.name }}"
          text: |
            **Host:** {{ item.name }}
            **ID:** {{ item.id }}
            {% if item.vars.zammad_info is defined %}
            **Zammad Version:** {{ item.vars.zammad_info.zammad_version | default('N/A') }}
            **RAM:** {{ item.vars.zammad_info.ram_gb | default('N/A') }} GB
            **OS:** {{ item.vars.zammad_info.os | default('N/A') }}
            **Status:** {{ 'Active' if item.vars.zammad_info.zammad_active | default(false) else 'Inactive' }}
            {% else %}
            No Zammad info available
            {% endif %}
          time: "{{ ansible_date_time.epoch | int }}000"
        validate_certs: no
        status_code: [200, 204]
      loop: "{{ parsed_hosts }}"
      loop_control:
        label: "{{ item.name }}"
      register: grafana_push_result
      failed_when: false

    - name: Report failed pushes
      debug:
        msg: "Failed to push {{ item.item.name }}: {{ item.msg | default('Unknown error') }}"
      loop: "{{ grafana_push_result.results }}"
      loop_control:
        label: "{{ item.item.name }}"
      when: item.failed | default(false)

    - name: Push inventory summary to Grafana
      uri:
        url: "{{ grafana_url }}/api/annotations"
        method: POST
        headers:
          Authorization: "Bearer {{ grafana_token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          tags:
            - "awx_inventory_sync"
            - "{{ awx_inventory_name }}"
          text: |
            **Inventory Sync Complete**
            Inventory: {{ awx_inventory_name }}
            Total Hosts: {{ parsed_hosts | length }}
            Successfully Pushed: {{ grafana_push_result.results | selectattr('failed','undefined') | list | length }}
            Failed: {{ grafana_push_result.results | selectattr('failed','defined') | selectattr('failed') | list | length }}
          time: "{{ ansible_date_time.epoch | int }}000"
        validate_certs: no
        status_code: [200, 204]
      when: parsed_hosts | length > 0

    - name: Final Summary
      debug:
        msg: |
          ========================================
          AWX → Grafana Sync Complete
          Inventory: {{ awx_inventory_name }}
          Total Hosts: {{ parsed_hosts | length }}
          Successfully Pushed: {{ grafana_push_result.results | selectattr('failed','undefined') | list | length }}
          Failed: {{ grafana_push_result.results | selectattr('failed','defined') | selectattr('failed') | list | length }}
          Grafana URL: {{ grafana_url }}
          Timestamp: {{ ansible_date_time.iso8601 }}
          ========================================
