---
- name: Extract AWX Host Data and Push to Grafana
  hosts: localhost
  gather_facts: no
  connection: local
  become: no

  vars:
    postgres_host: "{{ AWX_POSTGRES_HOST | default('awx-postgres-15') }}"
    postgres_port: "{{ AWX_POSTGRES_PORT | default('5432') }}"
    postgres_db: "{{ AWX_POSTGRES_DB | default('awx') }}"
    postgres_user: "{{ AWX_POSTGRES_USER | default('awx') }}"
    inventory_name: "{{ awx_inventory_name | default('test-inv') }}"
    grafana_url: "{{ GRAFANA_URL | default('') }}"
    grafana_token: "{{ GRAFANA_TOKEN | default('') }}"

  tasks:
    - name: Install required Python packages
      pip:
        name:
          - psycopg2-binary
        state: present
      ignore_errors: yes

    - name: Install required system packages (jq and kubectl)
      shell: |
        which jq || (apt-get update && apt-get install -y jq 2>/dev/null || yum install -y jq 2>/dev/null || apk add jq 2>/dev/null || echo "jq install skipped")
        which kubectl || (curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && chmod +x kubectl && mv kubectl /usr/local/bin/ 2>/dev/null || echo "kubectl install skipped")
      ignore_errors: yes
      changed_when: false

    - name: Get PostgreSQL credentials from Kubernetes secret
      shell: |
        kubectl get secret -n awx awx-postgres-configuration -o jsonpath='{.data}' | jq -r 'to_entries[] | "\(.key)=\(.value | @base64d)"' > /tmp/pg_creds.conf
      ignore_errors: yes
      changed_when: false
      no_log: true

    - name: Create Python script to query database
      copy:
        content: |
          #!/usr/bin/env python3
          import json
          import psycopg2
          import sys
          
          # Read credentials from file
          creds = {}
          try:
              with open('/tmp/pg_creds.conf', 'r') as f:
                  for line in f:
                      key, value = line.strip().split('=', 1)
                      creds[key] = value
          except Exception as e:
              print(json.dumps([{"error": f"Failed to read credentials: {str(e)}"}]))
              sys.exit(0)
          
          postgres_host = creds.get('host', '{{ postgres_host }}')
          postgres_port = creds.get('port', '{{ postgres_port }}')
          postgres_db = creds.get('database', '{{ postgres_db }}')
          postgres_user = creds.get('username', '{{ postgres_user }}')
          postgres_password = creds.get('password', '')
          inventory_name = "{{ inventory_name }}"
          
          try:
              conn = psycopg2.connect(
                  host=postgres_host,
                  port=int(postgres_port),
                  database=postgres_db,
                  user=postgres_user,
                  password=postgres_password
              )
              
              cur = conn.cursor()
              cur.execute("""
                  SELECT json_agg(row_to_json(t))
                  FROM (
                      SELECT 
                          h.id,
                          h.name,
                          h.variables
                      FROM main_host h
                      JOIN main_inventory i ON h.inventory_id = i.id
                      WHERE i.name = %s
                      ORDER BY h.name
                  ) t
              """, (inventory_name,))
              
              result = cur.fetchone()
              if result and result[0]:
                  print(json.dumps(result[0]))
              else:
                  print("[]")
              
              cur.close()
              conn.close()
          except Exception as e:
              print(json.dumps([{"error": str(e)}]))
              sys.exit(0)
        dest: /tmp/query_awx_db.py
        mode: '0755'

    - name: Run Python query script
      shell: python3 /tmp/query_awx_db.py
      register: db_query_result
      ignore_errors: yes
      changed_when: false

    - name: Set hosts data
      set_fact:
        hosts_data: "{{ db_query_result.stdout | from_json | default([]) }}"
      ignore_errors: yes

    - name: Convert dict response to list
      set_fact:
        hosts_data: "{{ [hosts_data] if hosts_data is mapping and 'name' in hosts_data else (hosts_data if hosts_data is iterable and hosts_data is not string else []) }}"

    - name: Show queried hosts
      debug:
        msg: "Found {{ hosts_data | length }} hosts from AWX"

    - name: DEBUG - Show detailed hosts data
      debug:
        msg: |
          Hosts data type: {{ hosts_data | type_debug }}
          Hosts data content: {{ hosts_data }}
          Grafana URL: {{ grafana_url }}
          Grafana token length: {{ grafana_token | length }}

    - name: DEBUG - Show first host details
      debug:
        msg: |
          First host: {{ hosts_data[0] | default('NO DATA') }}
      when: hosts_data | length > 0

    - name: Push host data to Grafana as annotations
      uri:
        url: "{{ grafana_url }}/api/annotations"
        method: POST
        headers:
          Authorization: "Bearer {{ grafana_token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          dashboardId: 0
          panelId: 0
          tags:
            - "zammad_inventory"
            - "{{ item.name }}"
          text: |
            **Host:** {{ item.name }}
            Zammad: {{ (item.variables | from_json).zammad_info.zammad_version | default('-') }}
            Redis: {{ (item.variables | from_json).redis_info.version | default('-') }}
            Elasticsearch: {{ (item.variables | from_json).elasticsearch_info.version | default('-') }}
            RAM: {{ (item.variables | from_json).zammad_info.ram_gb | default('-') }} GB
            Status: {{ 'Active' if (item.variables | from_json).zammad_info.zammad_active else 'Inactive' }}
            OS: {{ (item.variables | from_json).zammad_info.os | default('-') }}
            IP: {{ (item.variables | from_json).zammad_info.ip_address | default('-') }}
            Owner: {{ (item.variables | from_json).zammad_info.owner | default('-') }}
          time: "{{ ansible_date_time.epoch | int }}000"
        validate_certs: no
      loop: "{{ hosts_data }}"
      when: 
        - hosts_data | length > 0
        - grafana_token | length > 0
      ignore_errors: yes

    - name: Cleanup credentials file
      file:
        path: /tmp/pg_creds.conf
        state: absent
      ignore_errors: yes

    - name: Summary
      debug:
        msg: |
          ========================================
          Zammad to Grafana Push Complete
          ========================================
          Hosts processed: {{ hosts_data | length }}
          Grafana URL: {{ grafana_url }}
          Timestamp: {{ ansible_date_time.iso8601 }}
          ========================================