---
- name: Export AWX Inventory Hosts to Grafana
  hosts: localhost
  gather_facts: false
  vars:
    awx_inventory_name: "{{ AWX_INVENTORY_NAME }}"

  tasks:

    # -----------------------------
    # 1️⃣ Map environment variables
    # -----------------------------
    - name: Set database variables from environment
      set_fact:
        postgres_host: "{{ AWX_POSTGRES_HOST }}"
        postgres_port: "{{ AWX_POSTGRES_PORT | int }}"
        postgres_db: "{{ AWX_POSTGRES_DB }}"
        postgres_user: "{{ AWX_POSTGRES_USER }}"
        postgres_password: "{{ AWX_POSTGRES_PASSWORD }}"

    - name: Set Grafana variables from environment
      set_fact:
        grafana_url: "{{ GRAFANA_URL }}"
        grafana_token: "{{ GRAFANA_TOKEN }}"

    # -----------------------------
    # 2️⃣ Validate required environment variables
    # -----------------------------
    - name: Validate required environment variables
      assert:
        that:
          - postgres_host is defined and postgres_host != ''
          - postgres_port is defined
          - postgres_db is defined and postgres_db != ''
          - postgres_user is defined and postgres_user != ''
          - grafana_url is defined and grafana_url != ''
          - grafana_token is defined and grafana_token != ''
        fail_msg: "One or more required environment variables are missing."

    # -----------------------------
    # 3️⃣ Query AWX inventory hosts
    # -----------------------------

    - name: Query AWX inventory hosts
      community.postgresql.postgresql_query:
        login_host: "{{ AWX_POSTGRES_HOST }}"
        login_port: "{{ AWX_POSTGRES_PORT | int }}"
        login_user: "{{ AWX_POSTGRES_USER }}"
        login_password: "{{ AWX_POSTGRES_PASSWORD | trim }}"
        login_db: "{{ AWX_POSTGRES_DB }}"   # <-- use login_db (or 'db' as legacy alias)
        query: |
          SELECT h.id, h.name, h.variables
          FROM main_host h
          JOIN main_inventory i ON h.inventory_id = i.id
          WHERE i.name = %s
          ORDER BY h.name
        positional_args:
          - "{{ AWX_INVENTORY_NAME }}"
        login_unix_socket: ''
      register: pg_query
      delegate_to: localhost


    # Use the result set that your EE returns: query_all_results
    - name: Normalize rows list (support multiple return shapes)
      set_fact:
        _raw_rows: >-
          {{
            pg_query.query_all_results | default([]) | length > 0
            | ternary(pg_query.query_all_results[0],
                      pg_query.rows | default(pg_query.results[0].rows | default([])))
          }}

    # Build parsed_hosts from dict rows: each item is {'id':..., 'name':..., 'variables': '...json...'}
    - name: Init parsed_hosts
      set_fact:
        parsed_hosts: []

    - name: Build parsed_hosts objects (decode JSON)
      set_fact:
        parsed_hosts: >-
          {{
            parsed_hosts + [ {
              'id': item.id | default(item['id']),
              'name': item.name | default(item['name']),
              'vars': (
                (item.variables | default('{}')) is string
              ) | ternary( (item.variables | default('{}') | from_json), (item.variables | default({})) )
            } ]
          }}
      loop: "{{ _raw_rows }}"
      loop_control:
        label: "{{ (item.name | default(item['name'])) | default('row') }}"


    # -----------------------------
    # 4️⃣ Push inventory to Grafana (example)
    # -----------------------------
    - name: Show host count
      debug:
        msg: "Found {{ parsed_hosts | length }} hosts in inventory '{{ awx_inventory_name }}'"

    - name: Push each host to Grafana annotations
      uri:
        url: "{{ grafana_url }}/api/annotations"
        method: POST
        headers:
          Authorization: "Bearer {{ grafana_token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          tags:
            - "awx_inventory"
            - "{{ awx_inventory_name }}"
            - "{{ item.name }}"
          text: |
            **Host:** {{ item.name }}
            **ID:** {{ item.id }}
            {% if item.vars.zammad_info is defined %}
            **Zammad Version:** {{ item.vars.zammad_info.zammad_version | default('N/A') }}
            **RAM:** {{ item.vars.zammad_info.ram_gb | default('N/A') }} GB
            **OS:** {{ item.vars.zammad_info.os | default('N/A') }}
            **Status:** {{ 'Active' if item.vars.zammad_info.zammad_active | default(false) else 'Inactive' }}
            {% else %}
            No Zammad info available
            {% endif %}
          time: "{{ ansible_date_time.epoch | int }}000"
        validate_certs: no
        status_code: [200, 204]
      loop: "{{ parsed_hosts }}"
      loop_control:
        label: "{{ item.name }}"
      register: grafana_push_result
      failed_when: false

    - name: Report failed pushes
      debug:
        msg: "Failed to push {{ item.item.name }}: {{ item.msg | default('Unknown error') }}"
      loop: "{{ grafana_push_result.results }}"
      loop_control:
        label: "{{ item.item.name }}"
      when: item.failed | default(false)

    - name: Push inventory summary to Grafana
      uri:
        url: "{{ grafana_url }}/api/annotations"
        method: POST
        headers:
          Authorization: "Bearer {{ grafana_token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          tags:
            - "awx_inventory_sync"
            - "{{ awx_inventory_name }}"
          text: |
            **Inventory Sync Complete**
            Inventory: {{ awx_inventory_name }}
            Total Hosts: {{ parsed_hosts | length }}
            Successfully Pushed: {{ grafana_push_result.results | selectattr('failed','undefined') | list | length }}
            Failed: {{ grafana_push_result.results | selectattr('failed','defined') | selectattr('failed') | list | length }}
          time: "{{ (now() | to_datetime | to_timestamp | int) }}000"

        validate_certs: no
        status_code: [200, 204]
      when: parsed_hosts | length > 0

    - name: Final Summary
      debug:
        msg: |
          ========================================
          AWX → Grafana Sync Complete
          Inventory: {{ awx_inventory_name }}
          Total Hosts: {{ parsed_hosts | length }}
          Successfully Pushed: {{ grafana_push_result.results | selectattr('failed','undefined') | list | length }}
          Failed: {{ grafana_push_result.results | selectattr('failed','defined') | selectattr('failed') | list | length }}
          Grafana URL: {{ grafana_url }}
          Timestamp: {{ (now() | to_datetime).isoformat() }}
          ========================================
