---
# =========================================
# Play 1: Collect Zammad Facts per Host
# =========================================
- name: Collect Zammad Instance Information
  hosts: zammad_servers
  gather_facts: yes
  become: yes
  tasks:

    - name: Collect custom Zammad facts
      set_fact:
        zammad_info:
          hostname: "{{ inventory_hostname }}"
          ip_address: "{{ ansible_default_ipv4.address | default('Unknown') }}"
          owner: "{{ zammad_owner | default('Unknown') }}"
          state: "{{ zammad_state | default('Unknown') }}"
          os: "{{ ansible_facts['ansible_distribution'] }} {{ ansible_facts['ansible_distribution_version'] }}"
          ram_gb: "{{ (ansible_facts['ansible_memtotal_mb'] | int / 1024) | round(1) }}"
          zammad_version: "{{ zammad_version | default('Not Installed') }}"
          zammad_active: "{{ zammad_active | default(false) }}"
          zammad_enabled: "{{ zammad_enabled | default(false) }}"
          redis_version: "{{ redis_version | default('Not Available') }}"
          elasticsearch_version: "{{ elasticsearch_version | default('Not Available') }}"
          kit_packages: "{{ kit_packages | default({}) }}"
          other_packages: "{{ other_packages | default([]) }}"

# =========================================
# Play 2: Generate Centralized Reports
# =========================================
- name: Generate Centralized Reports
  hosts: localhost
  gather_facts: no
  connection: local
  become: no
  vars:
    reports_dir: /runner/artifacts/zammad_reports
  tasks:

    - name: Ensure reports directory exists
      file:
        path: "{{ reports_dir }}"
        state: directory
        mode: '0755'

    - name: Generate JSON report
      copy:
        dest: "{{ reports_dir }}/zammad_inventory_full.json"
        content: "{{ hostvars | json_query('*.zammad_info') | to_nice_json }}"

    - name: Generate Markdown report
      copy:
        dest: "{{ reports_dir }}/zammad_inventory_report.md"
        content: |
          # Zammad Infrastructure Inventory Report
          **Generated:** {{ now(utc=True).isoformat() }}
          **Total Hosts:** {{ groups['zammad_servers'] | length }}

          ---
          {% for host in groups['zammad_servers'] | sort %}
          {% set info = hostvars[host].zammad_info | default({}) %}
          ## {{ info.hostname | default(host) }}

          - **IP Address:** {{ info.ip_address | default('Unknown') }}
          - **Owner:** {{ info.owner | default('Unknown') }}
          - **State:** {{ info.state | default('Unknown') }}
          - **OS:** {{ info.os | default('Unknown') }}
          - **RAM:** {{ info.ram_gb | default('Unknown') }} GB
          - **Zammad Version:** {{ info.zammad_version | default('Not Installed') }}
          - **Redis Version:** {{ info.redis_version | default('Not Available') }}
          - **Elasticsearch Version:** {{ info.elasticsearch_version | default('Not Available') }}
          - **Service Active:** {{ 'Yes' if info.zammad_active | default(false) else 'No' }}
          - **Service Enabled:** {{ 'Yes' if info.zammad_enabled | default(false) else 'No' }}

          ### KIT Packages
          {% set kp = info.kit_packages | default({}) %}
          - **KIT-Customizations:** {{ kp['KIT-Customizations'] | default('-') }}
          - **KIT-Filter:** {{ kp['KIT-Filter'] | default('-') }}
          - **KIT-Form:** {{ kp['KIT-Form'] | default('-') }}
          - **KIT-Mobile:** {{ kp['KIT-Mobile'] | default('-') }}
          - **KIT-Newsletter:** {{ kp['KIT-Newsletter'] | default('-') }}
          - **KIT-Trigger:** {{ kp['KIT-Trigger'] | default('-') }}

          ### Other Packages
          {{ kp.other_packages | default('None') }}

          ---
          {% endfor %}

    - name: Generate CSV report
      copy:
        dest: "{{ reports_dir }}/zammad_inventory_report.csv"
        content: |
          Hostname,IP Address,Owner,State,OS,RAM (GB),Zammad Version,Redis,Elasticsearch,Service Active,Service Enabled,KIT-Customizations,KIT-Filter,KIT-Form,KIT-Mobile,KIT-Newsletter,KIT-Trigger,Other Packages
          {% for host in groups['zammad_servers'] | sort %}
          {% set info = hostvars[host].zammad_info | default({}) %}
          {{ info.hostname | default(host) }},
          {{ info.ip_address | default('Unknown') }},
          {{ info.owner | default('Unknown') }},
          {{ info.state | default('Unknown') }},
          {{ info.os | default('Unknown') }},
          {{ info.ram_gb | default('Unknown') }},
          {{ info.zammad_version | default('Not Installed') }},
          {{ info.redis_version | default('Not Available') }},
          {{ info.elasticsearch_version | default('Not Available') }},
          {{ 'Yes' if info.zammad_active | default(false) else 'No' }},
          {{ 'Yes' if info.zammad_enabled | default(false) else 'No' }},
          {{ info.kit_packages['KIT-Customizations'] | default('-') }},
          {{ info.kit_packages['KIT-Filter'] | default('-') }},
          {{ info.kit_packages['KIT-Form'] | default('-') }},
          {{ info.kit_packages['KIT-Mobile'] | default('-') }},
          {{ info.kit_packages['KIT-Newsletter'] | default('-') }},
          {{ info.kit_packages['KIT-Trigger'] | default('-') }},
          {{ info.other_packages | default([]) | join('; ') }}
          {% endfor %}

# =========================================
# Play 3: Display Summary
# =========================================
- name: Display Summary of Generated Reports
  hosts: localhost
  gather_facts: no
  connection: local
  become: no
  vars:
    reports_dir: /runner/artifacts/zammad_reports
  tasks:

    - name: Show Zammad report locations
      debug:
        msg: |
          ========================================
          Zammad Inventory Collection Complete
          ========================================
          Report Locations:
            - JSON: {{ reports_dir }}/zammad_inventory_full.json
            - CSV:  {{ reports_dir }}/zammad_inventory_report.csv
            - MD:   {{ reports_dir }}/zammad_inventory_report.md

          Total Hosts: {{ groups['zammad_servers'] | length }}
          Timestamp: {{ now(utc=True).isoformat() }}
          ========================================