all:
  children:
    zammad_servers:
      hosts:
        grafana-test.scc.kit.edu:
          ansible_host: 141.52.225.35
          state: Test
          owner: LB
        helpdesk-test.scc.kit.edu:
          ansible_host: 141.52.225.23
          state : Test
          owner: AH
        # eosc-helpdesk-dev.scc.kit.edu:
        #   ansible_host: 141.52.225.7
        #   state: Frozen   
        #   owner: PW
        eunode-helpdesk-dev.scc.kit.edu:
          ansible_host: 141.52.225.46
          state: Test
          owner: PW
        zammad-helpdesk-dev.scc.kit.edu:
          ansible_host: 141.52.225.15
          state: Frozen   
          owner: PW





      vars:
        ansible_connection: ssh
        ansible_user: root
        ansible_ssh_private_key_file: ~/.ssh/id_ed25519
        ansible_python_interpreter: /usr/bin/python3
        # hd-ops.scc.kit.edu:
        #   ansible_host: 141.52.225.103
        #   state: Prod
        #   owner: AH
        # eunode-helpdesk.scc.kit.edu:
        #   ansible_host: 141.52.225.39
        #   state: Prod
        #   owner: PW
        # bwcloud-helpdesk.scc.kit.edu:
        #   ansible_host: 129.13.64.28
        #   state: Prod
        #   owner: AH
        # beyond-helpdesk.scc.kit.edu:
        #   ansible_host: 141.52.225.8
        #   state: Prod
        #   owner: PW
        # helpdesk.services.ai4os.eu:
        #   ansible_host: 172.16.44.179
        #   state: Test
        #   owner: AH
        # helpdesk-adapter.scc.kit.edu:
        #   ansible_host: 141.52.225.68
        #   state: n8n
        #   owner: CM
        # nfdi-beyond-helpdesk.scc.kit.edu:
        #   ansible_host: 141.52.225.72
        #   state: Frozen
        #   owner: AH
        # hd-ops.scc.kit.edu:
        #   ansible_host:  141.52.225.103
        #   state: Prod
        #   owner: AH
        # nfdi4ing-helpdesk-test.scc.kit.edu:
        #   ansible_host: 141.52.225.34
        #   state: Test
        #   owner: AH
        # instruct-helpdesk.scc.kit.edu:
        #   ansible_host: 141.52.225.42
        #   state: Test
        #   owner: PW
        # zammadtest.scc.kit.edu:
        #   ansible_host: 141.52.225.67
        #   state: Test
        #   owner: AH
        # egi-helpdesk.scc.kit.edu:
        #   ansible_host: 141.52.225.114
        #   state: Frozen     
        #   owner: AH
        # nfdi-helpdesk.scc.kit.edu:
        #   ansible_host: 141.52.225.33
        #   state: Test
        #   owner: AH
        # eunode-helpdesk.scc.kit.edu:
        #   ansible_host: 141.52.225.39
        #   state: Prod
        #   owner: PW
        # eunode-helpdesk-stage.scc.kit.edu:
        #   ansible_host: 141.52.225.32
        #   state: Test
        #   owner: PW
        # premotec-helpdesk.scc.kit.edu:
        #   ansible_host: 141.52.225.18
        #   state: Test
        #   owner: PW
        # eosc-helpdesk.scc.kit.edu:
        #   ansible_host: 141.52.225.14
        #   state: Prod     
        #   owner: PW
        # eosc-helpdesk-dev.scc.kit.edu:
        #   ansible_host: 141.52.225.7
        #   state: Frozen   
        #   owner: PW

        # eucaim-helpdesk.scc.kit.edu:
        #   ansible_host: 141.52.225.29
        #   state: Prod    
        #   owner: AH 
        # hpc-dic-support.scc.kit.edu: 
        #   ansible_host: 141.52.225.19
        #   state: Prod     
        #   owner: PW
        # helpdesk.ggus.eu:
        #   ansible_host: 141.52.225.55
        #   state: Prod
        #   owner: "AH,PW"
        # helpdesk-stage.ggus.eu:
        #   ansible_host: 141.52.225.102
        #   state: Test 
        #   owner: "AH,PW"
        # helpdesk-dev.ggus.eu:
        #   ansible_host: 141.52.225.116
        #   state: Test   
        #   owner: "AH,PW"  
        # helpdesk-test.scc.kit.edu:
        #   ansible_host: 141.52.225.23
        #   state : Test
        #   owner: AH
        # ans-helpdesk.scc.kit.edu:
        #   ansible_host: 141.52.225.88
        #   state: Test
        #   owner: AH
        # ggus2.scc.kit.edu:
        #   ansible_host: 141.52.225.27
        #   state: Prod
        #   owner: PW
        # svmon.scc.kit.edu:
        #   ansible_host: 141.52.225.9
        #   state: Prod
        #   owner: null
        # mattermost-eudat-new.scc.kit.edu:
        #   ansible_host: 141.52.225.82
        #   state: Prod
        #   owner: AH
        # d3a-hv-ext.scc.kit.edu:
        #   ansible_host:  141.52.224.4
        #   state: Prod
        #   owner: JM
        # gitlab-eudat-new.scc.kit.edu:
        #   ansible_host: 141.52.225.96
        #   state: Prod
        #   owner: "AH,PW,JM"
        # eudat-runner.scc.kit.edu:
        #   ansible_host: 141.52.224.6
        #   state: Prod
        #   owner: JM
        # containers.scc.kit.edu:
        #     ansible_host: 141.52.225.28
        #     state: Prod
        #     owner: JM
        # containers-dev.scc.kit.edu:
        #     ansible_host: 141.52.225.22
        #     state: Test
        #     owner: JM
        # b2share-ibpt.scc.kit.edu:
        #     ansible_host: null
        #     state: null
        # irods-gfz-eudat.scc.kit.edu:
        #     ansible_host: 141.52.225.17
        #     state: Prod
        #     owner: JM

